# Generated by Django 4.2.23 on 2025-08-28 03:19

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import apps.media_assets.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="资产标题 (Title)")),
                ("description", models.TextField(blank=True, null=True, verbose_name="描述")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("short_drama", "短剧"), ("movie", "电影")],
                        default="short_drama",
                        max_length=20,
                        verbose_name="资产类型",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("zh-CN", "中文 (简体)"), ("en-US", "英语 (美国)")],
                        default="zh-CN",
                        max_length=10,
                        verbose_name="语言",
                    ),
                ),
                (
                    "copyright_status",
                    models.CharField(
                        choices=[("pending", "待定"), ("cleared", "已授权"), ("owned", "自有版权"), ("restricted", "受限")],
                        default="pending",
                        max_length=20,
                        verbose_name="版权状态",
                    ),
                ),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "等待文件上传"),
                            ("uploading", "上传中"),
                            ("completed", "上传完成"),
                            ("failed", "上传失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="文件上传状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "内容资产 (Asset)",
                "verbose_name_plural": "内容资产 (Asset)",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="媒体标题")),
                ("sequence_number", models.PositiveIntegerField(default=1, verbose_name="序号")),
                (
                    "source_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.media_assets.models.get_media_upload_path,
                        verbose_name="源视频文件",
                    ),
                ),
                (
                    "source_subtitle",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.media_assets.models.get_subtitle_upload_path,
                        verbose_name="源字幕文件 (SRT)",
                    ),
                ),
                (
                    "processed_video_url",
                    models.URLField(blank=True, max_length=1024, null=True, verbose_name="处理后视频URL (CDN)"),
                ),
                (
                    "source_subtitle_url",
                    models.URLField(blank=True, max_length=1024, null=True, verbose_name="源字幕文件URL (CDN/Public)"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="media_assets.asset",
                        verbose_name="所属资产 (Asset)",
                    ),
                ),
            ],
            options={
                "verbose_name": "媒体文件 (Media)",
                "verbose_name_plural": "媒体文件 (Media)",
                "ordering": ["asset", "sequence_number"],
            },
        ),
    ]
