# Generated by Django 4.2.23 on 2025-12-02 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="processed_video_url",
        ),
        migrations.RemoveField(
            model_name="media",
            name="source_subtitle_url",
        ),
    ]
