# Generated by Django 4.2.23 on 2025-12-09 03:25

from django.db import migrations, models

import apps.media_assets.models


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0002_remove_media_processed_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="waveform_data",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.media_assets.models.get_waveform_upload_path,
                verbose_name="波形数据 (Peaks)",
            ),
        ),
    ]
