# Generated by Django 4.2.23 on 2025-12-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0003_media_waveform_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="duration",
            field=models.FloatField(default=0.0, help_text="视频精确时长，由转码任务自动更新", verbose_name="时长 (秒)"),
        ),
    ]
