# Generated by Django 4.2.23 on 2025-08-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "oidc_rp_client_id",
                    models.CharField(
                        blank=True,
                        help_text="在 Authentik 中为 VSS-Workbench 创建的 Provider 所对应的 Client ID。",
                        max_length=255,
                        verbose_name="Django OIDC 客户端ID",
                    ),
                ),
                (
                    "oidc_rp_client_secret",
                    models.CharField(
                        blank=True,
                        help_text="在 Authentik 中为 VSS-Workbench 创建的 Provider 所对应的 Client Secret。",
                        max_length=255,
                        verbose_name="Django OIDC 客户端密钥",
                    ),
                ),
                (
                    "superuser_emails",
                    models.TextField(
                        blank=True,
                        help_text="用户首次通过 OIDC 登录时，如果其邮箱在此列表内，将自动被提升为超级管理员。每行一个邮箱地址。",
                        verbose_name="超级管理员邮箱列表",
                    ),
                ),
            ],
            options={
                "verbose_name": "集成设置",
            },
        ),
    ]
