# Generated by Django 4.2.23 on 2025-08-12 04:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integrationsettings",
            name="oidc_rp_client_id",
        ),
        migrations.RemoveField(
            model_name="integrationsettings",
            name="oidc_rp_client_secret",
        ),
    ]
