# Generated by Django 4.2.24 on 2025-09-10 11:14

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_remove_integrationsettings_oidc_rp_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='例如：H.264 1080p (5Mbps)', max_length=255, unique=True, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('container', models.CharField(default='mp4', help_text='例如：mp4, mov', max_length=10, verbose_name='输出容器格式')),
                ('ffmpeg_command', models.TextField(help_text='使用 {input_path} 和 {output_path} 作为占位符。例如：-c:v libx264 -b:v 5M -vf scale=-2:1080 -preset fast', verbose_name='FFmpeg 参数模板')),
            ],
            options={
                'verbose_name': '编码配置',
                'verbose_name_plural': '编码配置',
                'ordering': ['-created'],
            },
        ),
    ]
