# Generated by Django 4.2.23 on 2025-12-10 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0006_integrationsettings_label_studio_access_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integrationsettings",
            name="label_studio_access_token",
        ),
    ]
