# Generated by Django 4.2.23 on 2025-12-02 08:31

import uuid

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import apps.workflow.annotation.jobs
import apps.workflow.annotation.projects
import apps.workflow.inference.projects


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuration", "0006_integrationsettings_label_studio_access_token"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("media_assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失败"),
                            ("L1_AUDIT_PROCESSING", "L1 审计中"),
                            ("L2_EXPORTING", "L2 导出中"),
                            ("L3_BLUEPRINT_PROCESSING", "L3 蓝图生成中"),
                            ("L3_METRICS_PROCESSING", "L3 矩阵计算中"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "label_studio_project_id",
                    models.IntegerField(blank=True, null=True, verbose_name="Label Studio 项目ID"),
                ),
                (
                    "label_studio_export_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.annotation.projects.get_ls_export_upload_path,
                        verbose_name="Label Studio 导出文件",
                    ),
                ),
                (
                    "character_audit_report",
                    models.FileField(
                        blank=True, null=True, upload_to="audit_reports/l1_character/", verbose_name="角色审计报告 (摘要)"
                    ),
                ),
                (
                    "character_occurrence_report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audit_reports/l1_character_occurrences/",
                        verbose_name="角色出现详情 (日志)",
                    ),
                ),
                ("blueprint_validation_report", models.JSONField(blank=True, null=True, verbose_name="叙事蓝图验证报告")),
                (
                    "final_blueprint_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.annotation.projects.get_blueprint_upload_path,
                        verbose_name="最终叙事蓝图 (JSON)",
                    ),
                ),
                (
                    "local_metrics_result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.annotation.projects.get_cloud_output_upload_path,
                        verbose_name="角色矩阵产出 (本地)",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
                (
                    "source_encoding_profile",
                    models.ForeignKey(
                        help_text="选择一个编码配置。标注工具将使用此配置转码后的视频，以加快加载速度。",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuration.encodingprofile",
                        verbose_name="源编码配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "标注项目",
                "verbose_name_plural": "标注项目",
            },
        ),
        migrations.CreateModel(
            name="TranscodingProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                ("status", django_fsm.FSMField(default="PENDING", max_length=50, verbose_name="项目状态")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcoding_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
                (
                    "encoding_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuration.encodingprofile",
                        verbose_name="编码配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "转码项目",
                "verbose_name_plural": "转码项目",
            },
        ),
        migrations.CreateModel(
            name="TranscodingJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="transcoding_outputs/", verbose_name="输出文件"),
                ),
                ("output_url", models.URLField(blank=True, max_length=1024, null=True, verbose_name="输出文件URL (CDN)")),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcoding_jobs",
                        to="media_assets.media",
                        verbose_name="关联媒体文件",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuration.encodingprofile",
                        verbose_name="转码规格",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcoding_jobs",
                        to="workflow.transcodingproject",
                        verbose_name="所属转码项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "转码任务日志",
                "verbose_name_plural": "转码任务日志",
            },
        ),
        migrations.CreateModel(
            name="InferenceProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "待处理"), ("PROCESSING", "处理中"), ("COMPLETED", "已完成"), ("FAILED", "失败")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="项目状态",
                    ),
                ),
                ("rag_total_scene_count", models.IntegerField(blank=True, null=True, verbose_name="RAG 语料场景总数")),
                (
                    "annotation_project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_project",
                        to="workflow.annotationproject",
                        verbose_name="关联的标注项目",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "L3 推理项目",
                "verbose_name_plural": "L3 推理项目",
            },
        ),
        migrations.CreateModel(
            name="InferenceJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("FACTS", "角色属性识别"), ("RAG_DEPLOYMENT", "知识图谱部署")], max_length=20, verbose_name="任务类型"
                    ),
                ),
                ("input_params", models.JSONField(blank=True, null=True, verbose_name="输入参数")),
                ("cloud_task_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="云端任务 ID")),
                (
                    "cloud_blueprint_path",
                    models.CharField(blank=True, max_length=1024, null=True, verbose_name="云端蓝图路径"),
                ),
                ("cloud_facts_path", models.CharField(blank=True, max_length=1024, null=True, verbose_name="云端角色属性路径")),
                (
                    "output_facts_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.inference.projects.get_cloud_output_upload_path,
                        verbose_name="角色属性产出 (JSON)",
                    ),
                ),
                (
                    "output_rag_report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.inference.projects.get_cloud_output_upload_path,
                        verbose_name="RAG 部署报告 (JSON)",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.inferenceproject",
                        verbose_name="所属推理项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "L3 推理子任务",
                "verbose_name_plural": "L3 推理子任务",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                ("source_object_id", models.PositiveIntegerField()),
                ("delivery_url", models.URLField(blank=True, max_length=1024, null=True, verbose_name="分发后URL (CDN)")),
                (
                    "source_content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "分发任务",
                "verbose_name_plural": "分发任务",
            },
        ),
        migrations.CreateModel(
            name="CreativeProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("default", "标准创作 (Director)"),
                            ("template", "母本模板 (Template)"),
                            ("batch", "批量衍生 (Batch)"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="项目类型",
                    ),
                ),
                (
                    "narration_script_file",
                    models.FileField(
                        blank=True, null=True, upload_to="creative/narration/", verbose_name="解说词脚本 (JSON)"
                    ),
                ),
                (
                    "localized_script_file",
                    models.FileField(
                        blank=True, null=True, upload_to="creative/localized/", verbose_name="本地化脚本 (JSON)"
                    ),
                ),
                (
                    "dubbing_script_file",
                    models.FileField(blank=True, null=True, upload_to="creative/dubbing/", verbose_name="配音脚本 (JSON)"),
                ),
                (
                    "edit_script_file",
                    models.FileField(blank=True, null=True, upload_to="creative/edit/", verbose_name="剪辑脚本 (JSON)"),
                ),
                (
                    "final_video_file",
                    models.FileField(blank=True, null=True, upload_to="creative/output/", verbose_name="最终成片"),
                ),
                ("auto_config", models.JSONField(blank=True, default=dict, verbose_name="参数配置快照")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("NARRATION_RUNNING", "Generating Narration"),
                            ("NARRATION_COMPLETED", "Narration Ready"),
                            ("LOCALIZATION_RUNNING", "Localizing"),
                            ("LOCALIZATION_COMPLETED", "Localized"),
                            ("AUDIO_RUNNING", "Generating Audio"),
                            ("AUDIO_COMPLETED", "Audio Ready"),
                            ("EDIT_RUNNING", "Generating Script"),
                            ("EDIT_COMPLETED", "Script Ready"),
                            ("SYNTHESIS_RUNNING", "Synthesizing"),
                            ("COMPLETED", "All Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="CREATED",
                        max_length=50,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
                (
                    "inference_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative_projects",
                        to="workflow.inferenceproject",
                        verbose_name="关联推理项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "创作项目 (Creative Project)",
                "verbose_name_plural": "创作项目 (Creative Projects)",
                "ordering": ["-modified"],
            },
        ),
        migrations.CreateModel(
            name="CreativeJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("GENERATE_NARRATION", "生成解说词"),
                            ("LOCALIZE_NARRATION", "本地化/翻译"),
                            ("GENERATE_AUDIO", "生成配音"),
                            ("GENERATE_EDIT_SCRIPT", "生成剪辑脚本"),
                            ("SYNTHESIS", "视频合成"),
                        ],
                        max_length=30,
                        verbose_name="任务类型",
                    ),
                ),
                ("input_params", models.JSONField(blank=True, null=True, verbose_name="输入参数")),
                ("cloud_task_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="云端任务 ID")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.creativeproject",
                        verbose_name="所属创作项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "子任务状态列表",
                "verbose_name_plural": "子任务状态列表",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("L1_SUBEDITING", "第一层-字幕"), ("L2L3_SEMANTIC", "第二三层-语义标注")],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                ("label_studio_task_id", models.IntegerField(blank=True, null=True, verbose_name="Label Studio 任务ID")),
                (
                    "l1_output_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(location="/app/media_root"),
                        upload_to=apps.workflow.annotation.jobs.get_l1_output_upload_path,
                        verbose_name="L1产出物 (.ass)",
                    ),
                ),
                (
                    "l1_version_backup_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(location="/app/media_root"),
                        upload_to=apps.workflow.annotation.jobs.get_l1_output_upload_path,
                        verbose_name="L1产出物备份",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_jobs",
                        to="media_assets.media",
                        verbose_name="关联媒体文件",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.annotationproject",
                        verbose_name="所属标注项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "标注任务",
                "verbose_name_plural": "标注任务",
                "ordering": ["-created"],
            },
        ),
    ]
