# Generated by Django 4.2.23 on 2025-08-28 06:35

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media_assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscodingProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                ("status", django_fsm.FSMField(default="PENDING", max_length=50, verbose_name="项目状态")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcoding_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "转码项目",
                "verbose_name_plural": "转码项目",
            },
        ),
        migrations.CreateModel(
            name="TranscodingJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("status", django_fsm.FSMField(default="QUEUED", max_length=50, protected=True, verbose_name="任务状态")),
                (
                    "profile",
                    models.CharField(
                        choices=[("H264_720P_2M", "H.264 720p (2Mbps)"), ("H264_1080P_5M", "H.264 1080p (5Mbps)")],
                        max_length=20,
                        verbose_name="转码规格",
                    ),
                ),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="transcoding_outputs/", verbose_name="输出文件"),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcoding_jobs",
                        to="media_assets.media",
                        verbose_name="关联媒体文件",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcoding_jobs",
                        to="workflow.transcodingproject",
                        verbose_name="所属转码项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "转码任务日志",
                "verbose_name_plural": "转码任务日志",
            },
        ),
        migrations.CreateModel(
            name="AnnotationProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                (
                    "label_studio_project_id",
                    models.IntegerField(blank=True, null=True, verbose_name="Label Studio 项目ID"),
                ),
                (
                    "label_studio_export_file",
                    models.FileField(blank=True, null=True, upload_to="ls_exports/", verbose_name="Label Studio 导出文件"),
                ),
                (
                    "character_audit_report",
                    models.FileField(
                        blank=True, null=True, upload_to="audit_reports/l1_character/", verbose_name="角色名审计报告 (CSV)"
                    ),
                ),
                ("blueprint_validation_report", models.JSONField(blank=True, null=True, verbose_name="叙事蓝图验证报告")),
                (
                    "final_blueprint_file",
                    models.FileField(blank=True, null=True, upload_to="blueprints/", verbose_name="最终叙事蓝图 (JSON)"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "标注项目",
                "verbose_name_plural": "标注项目",
            },
        ),
        migrations.CreateModel(
            name="AnnotationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("status", django_fsm.FSMField(default="QUEUED", max_length=50, protected=True, verbose_name="任务状态")),
                (
                    "job_type",
                    models.CharField(
                        choices=[("L1_SUBEDITING", "第一层-字幕"), ("L2L3_ANNOTATION", "第二三层-语义标注")],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_jobs",
                        to="media_assets.asset",
                        verbose_name="关联资产条目",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.annotationproject",
                        verbose_name="所属标注项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "标注任务",
                "verbose_name_plural": "标注任务",
                "ordering": ["-created"],
            },
        ),
    ]
