# Generated by Django 4.2.23 on 2025-08-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationjob',
            name='asset',
        ),
        migrations.AddField(
            model_name='annotationjob',
            name='label_studio_task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Label Studio 任务ID'),
        ),
        migrations.AddField(
            model_name='annotationjob',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_jobs', to='media_assets.media', verbose_name='关联媒体文件'),
        ),
        migrations.AlterField(
            model_name='annotationjob',
            name='job_type',
            field=models.CharField(choices=[('L1_SUBEDITING', '第一层-字幕'), ('L2L3_SEMANTIC', '第二三层-语义标注')], max_length=20, verbose_name='任务类型'),
        ),
    ]
