# Generated by Django 4.2.23 on 2025-12-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativeproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("NARRATION_RUNNING", "Generating Narration"),
                    ("NARRATION_COMPLETED", "Narration Ready"),
                    ("LOCALIZATION_RUNNING", "Localizing"),
                    ("LOCALIZATION_COMPLETED", "Localized"),
                    ("AUDIO_RUNNING", "Generating Audio"),
                    ("AUDIO_COMPLETED", "Audio Ready"),
                    ("EDIT_RUNNING", "Generating EditingScript"),
                    ("EDIT_COMPLETED", "EditingScript Ready"),
                    ("SYNTHESIS_RUNNING", "Synthesizing"),
                    ("COMPLETED", "All Done"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=50,
                verbose_name="当前状态",
            ),
        ),
    ]
