# Generated by Django 4.2.23 on 2025-12-10 08:31

import django.core.files.storage
from django.db import migrations, models

import apps.workflow.annotation.jobs
import apps.workflow.annotation.projects


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationjob",
            name="annotation_file_backup",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(location="/app/media_root"),
                upload_to=apps.workflow.annotation.jobs.get_annotation_upload_path,
                verbose_name="标注工程文件 (Backup)",
            ),
        ),
        migrations.AddField(
            model_name="annotationproject",
            name="annotation_audit_report_backup",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.workflow.annotation.projects.get_audit_upload_path,
                verbose_name="标注审计报告 (Backup)",
            ),
        ),
        migrations.AddField(
            model_name="annotationproject",
            name="final_blueprint_file_backup",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.workflow.annotation.projects.get_blueprint_upload_path,
                verbose_name="生产消费蓝图 (Backup)",
            ),
        ),
        migrations.AddField(
            model_name="annotationproject",
            name="project_export_file_backup",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.workflow.annotation.projects.get_project_export_path,
                verbose_name="工程全量导出 (Backup)",
            ),
        ),
        migrations.AlterField(
            model_name="annotationjob",
            name="annotation_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(location="/app/media_root"),
                upload_to=apps.workflow.annotation.jobs.get_annotation_upload_path,
                verbose_name="标注工程文件 (Current)",
            ),
        ),
        migrations.AlterField(
            model_name="annotationproject",
            name="annotation_audit_report",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.workflow.annotation.projects.get_audit_upload_path,
                verbose_name="标注审计报告 (Current)",
            ),
        ),
        migrations.AlterField(
            model_name="annotationproject",
            name="final_blueprint_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.workflow.annotation.projects.get_blueprint_upload_path,
                verbose_name="生产消费蓝图 (Current)",
            ),
        ),
        migrations.AlterField(
            model_name="annotationproject",
            name="project_export_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.workflow.annotation.projects.get_project_export_path,
                verbose_name="工程全量导出 (Current)",
            ),
        ),
    ]
