# Generated by Django 4.2.23 on 2025-08-28 10:09

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_remove_annotationjob_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationjob',
            name='status',
            field=django_fsm.FSMField(default='PENDING', max_length=50, protected=True, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='transcodingjob',
            name='status',
            field=django_fsm.FSMField(default='PENDING', max_length=50, protected=True, verbose_name='任务状态'),
        ),
    ]
