# Generated by Django 4.2.23 on 2025-12-08 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0002_alter_creativeproject_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationProjectV2",
            fields=[],
            options={
                "verbose_name": "标注项目 (V2 重构版)",
                "verbose_name_plural": "标注项目 (V2 重构版)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("workflow.annotationproject",),
        ),
    ]
