# Generated by Django 4.2.23 on 2025-08-28 10:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_annotationjob_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationjob',
            name='status',
            field=django_fsm.FSMField(choices=[('PENDING', '待处理'), ('QUEUED', '排队中'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('ERROR', '错误'), ('QA_PENDING', '待审核')], default='PENDING', max_length=50, protected=True, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='transcodingjob',
            name='status',
            field=django_fsm.FSMField(choices=[('PENDING', '待处理'), ('QUEUED', '排队中'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('ERROR', '错误'), ('QA_PENDING', '待审核')], default='PENDING', max_length=50, protected=True, verbose_name='任务状态'),
        ),
    ]
