# Generated by Django 4.2.23 on 2025-08-28 10:47
import django

from apps.workflow.annotation import jobs as annotationJob
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_annotationjob_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationjob',
            name='l1_output_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/media_root/annotation'), upload_to=annotationJob.get_l1_output_upload_path, verbose_name='L1产出物 (.ass)'),
        ),
    ]
