# Generated by Django 4.2.23 on 2025-08-29 01:25

import apps.workflow.jobs.annotationJob
import django.core.files.storage
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_annotationjob_l1_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationjob',
            name='l1_version_backup_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/media_root/annotation'), upload_to=apps.workflow.jobs.annotationJob.get_l1_output_upload_path, verbose_name='L1产出物备份'),
        ),
        migrations.AlterField(
            model_name='annotationjob',
            name='status',
            field=django_fsm.FSMField(choices=[('PENDING', '待处理'), ('QUEUED', '排队中'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('REVISING', '修订中'), ('ERROR', '错误'), ('QA_PENDING', '待审核')], default='PENDING', max_length=50, protected=True, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='transcodingjob',
            name='status',
            field=django_fsm.FSMField(choices=[('PENDING', '待处理'), ('QUEUED', '排队中'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('REVISING', '修订中'), ('ERROR', '错误'), ('QA_PENDING', '待审核')], default='PENDING', max_length=50, protected=True, verbose_name='任务状态'),
        ),
    ]
