# Generated by Django 4.2.23 on 2025-08-30 04:15

from apps.workflow.annotation import jobs as annotationJob

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_annotationproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationproject',
            name='blueprint_status',
            field=models.CharField(choices=[('PENDING', '未开始'), ('PROCESSING', '生成中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='蓝图生成状态'),
        ),
        migrations.AlterField(
            model_name='annotationjob',
            name='l1_output_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/media_root'), upload_to=annotationJob.get_l1_output_upload_path, verbose_name='L1产出物 (.ass)'),
        ),
        migrations.AlterField(
            model_name='annotationjob',
            name='l1_version_backup_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/media_root'), upload_to=annotationJob.get_l1_output_upload_path, verbose_name='L1产出物备份'),
        ),
    ]
