# Generated by Django 4.2.23 on 2025-08-30 04:16

import apps.workflow.projects.annotationProject
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_annotationproject_blueprint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationproject',
            name='final_blueprint_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflow.projects.annotationProject.get_blueprint_upload_path, verbose_name='最终叙事蓝图 (JSON)'),
        ),
        migrations.AlterField(
            model_name='annotationproject',
            name='label_studio_export_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflow.projects.annotationProject.get_ls_export_upload_path, verbose_name='Label Studio 导出文件'),
        ),
    ]
