# Generated by Django 4.2.24 on 2025-09-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0004_encodingprofile_is_default"),
        ("workflow", "0009_alter_annotationproject_final_blueprint_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcodingjob",
            name="output_url",
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name="输出文件URL (CDN)"),
        ),
        migrations.AlterField(
            model_name="transcodingjob",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="configuration.encodingprofile", verbose_name="转码规格"
            ),
        ),
    ]
