# Generated by Django 4.2.24 on 2025-09-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_encodingprofile_is_default'),
        ('workflow', '0010_transcodingjob_output_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodingproject',
            name='encoding_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.encodingprofile', verbose_name='编码配置'),
        ),
    ]
