# Generated by Django 4.2.24 on 2025-09-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0012_deliveryjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationproject",
            name="source_transcoding_project",
            field=models.ForeignKey(
                blank=True,
                help_text="（可选）选择一个已完成的转码项目。如果选择，标注工具将使用其转码后的 CDN 视频，以加快加载速度。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflow.transcodingproject",
                verbose_name="源转码项目",
            ),
        ),
    ]
