# Generated by Django 4.2.24 on 2025-09-15 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_encodingprofile_is_default'),
        ('workflow', '0013_annotationproject_source_transcoding_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationproject',
            name='source_transcoding_project',
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='source_encoding_profile',
            field=models.ForeignKey(help_text='选择一个编码配置。标注工具将使用此配置转码后的视频，以加快加载速度。', null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.encodingprofile', verbose_name='源编码配置'),
        ),
    ]
