# Generated by Django 4.2.25 on 2025-11-06 06:35

import apps.workflow.annotation.projects
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_remove_annotationproject_source_transcoding_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationproject',
            name='cloud_blueprint_path',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='云端蓝图路径'),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='cloud_facts_path',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='云端角色属性路径'),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='cloud_facts_result_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflow.annotation.projects.get_cloud_output_upload_path, verbose_name='角色属性产出 (JSON)'),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='cloud_metrics_result_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflow.annotation.projects.get_cloud_output_upload_path, verbose_name='角色矩阵产出 (JSON)'),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='cloud_rag_report_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflow.annotation.projects.get_cloud_output_upload_path, verbose_name='RAG 部署报告 (JSON)'),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='cloud_reasoning_error',
            field=models.TextField(blank=True, null=True, verbose_name='推理失败信息'),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='cloud_reasoning_status',
            field=models.CharField(choices=[('PENDING', '未开始'), ('BLUEPRINT_UPLOADING', '上传蓝图'), ('METRICS_RUNNING', '分析角色矩阵'), ('WAITING_FOR_SELECTION', '等待角色选择'), ('FACTS_RUNNING', '识别角色属性'), ('PIPELINE_RUNNING', '执行自动流水线'), ('RAG_DEPLOYING', '部署知识图谱'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=30, verbose_name='云端推理状态'),
        ),
    ]
