# Generated by Django 4.2.25 on 2025-11-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0015_annotationproject_cloud_blueprint_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationproject",
            name="character_occurrence_report",
            field=models.FileField(
                blank=True, null=True, upload_to="audit_reports/l1_character_occurrences/", verbose_name="角色出现详情 (日志)"
            ),
        ),
    ]
