# Generated by Django 4.2.25 on 2025-11-10 09:17

import apps.workflow.inference.projects
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
        ('workflow', '0017_annotationproject_local_metrics_result_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationproject',
            name='cloud_blueprint_path',
        ),
        migrations.RemoveField(
            model_name='annotationproject',
            name='cloud_facts_path',
        ),
        migrations.RemoveField(
            model_name='annotationproject',
            name='cloud_facts_result_file',
        ),
        migrations.RemoveField(
            model_name='annotationproject',
            name='cloud_metrics_result_file',
        ),
        migrations.RemoveField(
            model_name='annotationproject',
            name='cloud_rag_report_file',
        ),
        migrations.RemoveField(
            model_name='annotationproject',
            name='cloud_reasoning_error',
        ),
        migrations.RemoveField(
            model_name='annotationproject',
            name='cloud_reasoning_status',
        ),
        migrations.CreateModel(
            name='InferenceProject',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='项目状态')),
                ('cloud_reasoning_status', models.CharField(choices=[('PENDING', '未开始'), ('BLUEPRINT_UPLOADING', '上传蓝图'), ('METRICS_RUNNING', '分析角色矩阵'), ('WAITING_FOR_SELECTION', '等待角色选择'), ('FACTS_RUNNING', '识别角色属性'), ('PIPELINE_RUNNING', '执行自动流水线'), ('RAG_DEPLOYING', '部署知识图谱'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=30, verbose_name='云端推理状态')),
                ('cloud_reasoning_error', models.TextField(blank=True, null=True, verbose_name='推理失败信息')),
                ('cloud_blueprint_path', models.CharField(blank=True, max_length=1024, null=True, verbose_name='云端蓝图路径')),
                ('cloud_facts_path', models.CharField(blank=True, max_length=1024, null=True, verbose_name='云端角色属性路径')),
                ('cloud_facts_result_file', models.FileField(blank=True, null=True, upload_to=apps.workflow.inference.projects.get_cloud_output_upload_path, verbose_name='角色属性产出 (JSON)')),
                ('cloud_rag_report_file', models.FileField(blank=True, null=True, upload_to=apps.workflow.inference.projects.get_cloud_output_upload_path, verbose_name='RAG 部署报告 (JSON)')),
                ('annotation_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inference_project', to='workflow.annotationproject', verbose_name='关联的标注项目')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_projects', to='media_assets.asset', verbose_name='关联资产')),
            ],
            options={
                'verbose_name': 'L3 推理项目',
                'verbose_name_plural': 'L3 推理项目',
            },
        ),
    ]
