# Generated by Django 4.2.25 on 2025-11-11 02:15

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import apps.workflow.inference.projects


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0019_remove_annotationproject_blueprint_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inferenceproject",
            name="cloud_blueprint_path",
        ),
        migrations.RemoveField(
            model_name="inferenceproject",
            name="cloud_facts_path",
        ),
        migrations.RemoveField(
            model_name="inferenceproject",
            name="cloud_facts_result_file",
        ),
        migrations.RemoveField(
            model_name="inferenceproject",
            name="cloud_rag_report_file",
        ),
        migrations.RemoveField(
            model_name="inferenceproject",
            name="cloud_reasoning_error",
        ),
        migrations.RemoveField(
            model_name="inferenceproject",
            name="cloud_reasoning_status",
        ),
        migrations.AlterField(
            model_name="annotationproject",
            name="character_audit_report",
            field=models.FileField(
                blank=True, null=True, upload_to="audit_reports/l1_character/", verbose_name="角色审计报告 (摘要)"
            ),
        ),
        migrations.CreateModel(
            name="InferenceJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("FACTS", "角色属性识别"), ("RAG_DEPLOYMENT", "知识图谱部署")], max_length=20, verbose_name="任务类型"
                    ),
                ),
                ("input_params", models.JSONField(blank=True, null=True, verbose_name="输入参数")),
                ("cloud_task_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="云端任务 ID")),
                ("cloud_facts_path", models.CharField(blank=True, max_length=1024, null=True, verbose_name="云端角色属性路径")),
                (
                    "output_facts_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.inference.projects.get_cloud_output_upload_path,
                        verbose_name="角色属性产出 (JSON)",
                    ),
                ),
                (
                    "output_rag_report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.inference.projects.get_cloud_output_upload_path,
                        verbose_name="RAG 部署报告 (JSON)",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.inferenceproject",
                        verbose_name="所属推理项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "L3 推理子任务",
                "verbose_name_plural": "L3 推理子任务",
                "ordering": ["-created"],
            },
        ),
    ]
