# Generated by Django 4.2.25 on 2025-11-11 06:48

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import apps.workflow.creative.projects


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0001_initial"),
        ("workflow", "0021_inferencejob_cloud_blueprint_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreativeProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("NARRATION_RUNNING", "解说词生成中"),
                            ("NARRATION_COMPLETED", "解说词已完成"),
                            ("AUDIO_RUNNING", "配音生成中"),
                            ("AUDIO_COMPLETED", "配音已完成"),
                            ("EDIT_RUNNING", "剪辑脚本生成中"),
                            ("COMPLETED", "所有产出物已完成"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="创作项目状态",
                    ),
                ),
                (
                    "narration_script_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.creative.projects.get_creative_output_upload_path,
                        verbose_name="解说词脚本 (JSON)",
                    ),
                ),
                (
                    "dubbing_audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.creative.projects.get_creative_output_upload_path,
                        verbose_name="配音文件 (MP3/WAV)",
                    ),
                ),
                (
                    "edit_script_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.creative.projects.get_creative_output_upload_path,
                        verbose_name="剪辑脚本 (JSON/EDL)",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
                (
                    "inference_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creative_projects",
                        to="workflow.inferenceproject",
                        verbose_name="关联的推理项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "L4 创作项目",
                "verbose_name_plural": "L4 创作项目",
                "ordering": ["-modified"],
            },
        ),
        migrations.CreateModel(
            name="CreativeJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("GENERATE_NARRATION", "生成解说词"),
                            ("GENERATE_AUDIO", "生成配音"),
                            ("GENERATE_EDIT_SCRIPT", "生成剪辑脚本"),
                        ],
                        max_length=30,
                        verbose_name="任务类型",
                    ),
                ),
                ("input_params", models.JSONField(blank=True, null=True, verbose_name="输入参数")),
                ("cloud_task_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="云端任务 ID")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.creativeproject",
                        verbose_name="所属创作项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "L4 创作子任务",
                "verbose_name_plural": "L4 创作子任务",
                "ordering": ["-created"],
            },
        ),
    ]
