# Generated by Django 4.2.25 on 2025-11-11 09:59

import apps.workflow.creative.projects
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_creativeproject_creativejob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativeproject',
            name='dubbing_audio_file',
        ),
        migrations.AddField(
            model_name='creativeproject',
            name='dubbing_script_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflow.creative.projects.get_creative_output_upload_path, verbose_name='配音脚本 (JSON)'),
        ),
    ]
