# Generated by Django 4.2.25 on 2025-11-14 03:21

import django_fsm
from django.db import migrations, models

import apps.workflow.creative.projects


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0024_inferenceproject_rag_total_scene_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="creativeproject",
            name="final_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.workflow.creative.projects.get_creative_output_upload_path,
                verbose_name="最终合成视频 (MP4)",
            ),
        ),
        migrations.AlterField(
            model_name="creativeproject",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "待处理"),
                    ("NARRATION_RUNNING", "解说词生成中"),
                    ("NARRATION_COMPLETED", "解说词已完成"),
                    ("AUDIO_RUNNING", "配音生成中"),
                    ("AUDIO_COMPLETED", "配音已完成"),
                    ("EDIT_RUNNING", "剪辑脚本生成中"),
                    ("EDIT_COMPLETED", "剪辑脚本已完成"),
                    ("SYNTHESIS_RUNNING", "合成中"),
                    ("COMPLETED", "所有产出物已完成"),
                    ("FAILED", "失败"),
                ],
                default="PENDING",
                max_length=30,
                verbose_name="创作项目状态",
            ),
        ),
    ]
