# Generated by Django 4.2.25 on 2025-11-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0025_creativeproject_final_video_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativejob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("GENERATE_NARRATION", "生成解说词"),
                    ("GENERATE_AUDIO", "生成配音"),
                    ("GENERATE_EDIT_SCRIPT", "生成剪辑脚本"),
                    ("SYNTHESIS", "视频合成"),
                ],
                max_length=30,
                verbose_name="任务类型",
            ),
        ),
    ]
