# Generated by Django 4.2.26 on 2025-11-24 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_alter_creativejob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeproject',
            name='auto_config',
            field=models.JSONField(blank=True, null=True, verbose_name='自动化全流程配置 (Auto-Pilot)'),
        ),
        migrations.CreateModel(
            name='CreativeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_count', models.PositiveIntegerField(verbose_name='计划生成数量')),
                ('batch_strategy', models.JSONField(default=dict, verbose_name='编排策略快照')),
                ('inference_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.inferenceproject', verbose_name='源推理项目')),
            ],
            options={
                'verbose_name': '批量创作任务',
                'verbose_name_plural': '批量创作任务',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='creativeproject',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='workflow.creativebatch', verbose_name='所属批次'),
        ),
    ]
