# Generated by Django 4.2.26 on 2025-11-28 07:23

import apps.workflow.creative.projects
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_creativeproject_auto_config_creativebatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeproject',
            name='localized_script_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflow.creative.projects.get_creative_output_upload_path, verbose_name='本地化/翻译脚本 (JSON)'),
        ),
        migrations.AlterField(
            model_name='creativejob',
            name='job_type',
            field=models.CharField(choices=[('GENERATE_NARRATION', '生成解说词'), ('LOCALIZE_NARRATION', '本地化/翻译'), ('GENERATE_AUDIO', '生成配音'), ('GENERATE_EDIT_SCRIPT', '生成剪辑脚本'), ('SYNTHESIS', '视频合成')], max_length=30, verbose_name='任务类型'),
        ),
    ]
