# Generated by Django 4.2.26 on 2025-11-29 02:15

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0028_creativeproject_localized_script_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creativeproject",
            options={"ordering": ["-modified"], "verbose_name": "创作项目", "verbose_name_plural": "创作项目"},
        ),
        migrations.AlterField(
            model_name="creativeproject",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "排队待处理"),
                    ("NARRATION_RUNNING", "解说词生成中"),
                    ("NARRATION_COMPLETED", "解说词已完成"),
                    ("LOCALIZATION_RUNNING", "翻译中"),
                    ("LOCALIZATION_COMPLETED", "翻译已完成"),
                    ("AUDIO_RUNNING", "配音生成中"),
                    ("AUDIO_COMPLETED", "配音已完成"),
                    ("EDIT_RUNNING", "剪辑脚本生成中"),
                    ("EDIT_COMPLETED", "剪辑脚本已完成"),
                    ("SYNTHESIS_RUNNING", "合成中"),
                    ("COMPLETED", "所有产出物已完成"),
                    ("FAILED", "失败"),
                ],
                default="PENDING",
                max_length=30,
                verbose_name="创作项目状态",
            ),
        ),
    ]
