# Generated by Django 4.2.26 on 2025-11-29 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0029_alter_creativeproject_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creativejob",
            options={"ordering": ["-created"], "verbose_name": "创作子任务", "verbose_name_plural": "创作子任务"},
        ),
    ]
